name: submodule-update

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  image:
    name: submodule-update
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 1
      # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      # Commit and push
      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
